### ISSUE TITLE
Token issuer not allowed

### ISSUE THREAD

**Issue by ropi95** [gbbirkisson/kong-plugin-jwt-keycloak#13]
i use kong 1.0.0 with this jwt plugin, but when i try to acces gateway and try to use bearer, i got some error 

`{
    "message": "Token issuer not allowed"
}`

how to fix it? or setting it?
thank you anyway

i use this setting for keycloak : https://www.jerney.io/secure-apis-kong-keycloak-1/

**Comment by gbbirkisson** [comment]
When adding the plugin to the endpoint/route, what [allowed issuers](https://github.com/gbbirkisson/kong-plugin-jwt-keycloak#enabling-on-endpoints) did you set?

What is the issuer of the token you are using to access the API?

Do they match?

**Comment by ropi95** [comment]
what is allowed issuer? i dont understand, can you give me an example or references?

**Comment by gbbirkisson** [comment]
Each JWT token has a `iss` claim. To view your token claims you can paste it into https://jwt.io/

So if you are runnin keycloak locally, over http, the token issued by the master realm keycloak will probably have the claim `iss=http://localhost:8080/auth/realms/master`.

When adding the plugin to an endpoint, you have to specify, what token issuers are allowed on this endpoint. So if you want to allow your local keycloak master realm you would do something like:

```
curl -X POST http://localhost:8001/routes/{route_id}/plugins \
    --data "name=jwt-keycloak" \
    --data "config.allowed_iss=http://localhost:8080/auth/realms/master"
```

**Comment by ropi95** [comment]
i add this globally, i got new error {
    "message": "no Route matched with those values"
}

**Comment by ropi95** [comment]
and then, i add a service and got error `{
    "message": "Unable to get public key for issuer"
}`

**Comment by gbbirkisson** [comment]
The Kong process has to be able to call Keycloak to verify the tokens. If that fails, you get this error. I will add this comment to the README to be more specific on how this works.

I suggest that you read the README thoroughly and experiment a bit before you post issues. I cannot debug every issue you come across. If you have an issue that you cannot overcome, send me a thorough description on how to replicate the issue so I can address it.

**Comment by ropi95** [comment]
sorry, i mean,,  i add a route and got error { "message": "Unable to get public key for issuer" }

**Comment by ropi95** [comment]
```
To verify token issuers, this plugin needs to be able to access the <ISSUER_REALM_URL>/.well-known/openid-configuration and <ISSUER_REALM_URL>/protocol/openid-connect/certs endpoints of keycloak. If you are getting the error { "message": "Unable to get public key for issuer" } it is probably because for some reason the plugin is unable to access these endpoints.
```

how to check if plugin cannot acces it?

**Comment by gbbirkisson** [comment]
Like i said in a previous comment: 

> send me a thorough description on how to replicate the issue so I can address it

I'm going to close this issue. If you are still having trouble send this info and I will reopen it:
* Where is Keycloak running (locally, in docker, somewhere else?)
  * Are you using https, if so, are you using a self signed cert?
* Where is Kong running (locally, in docker, somewhere else?)
* How did you apply this plugin, send me the whole request you sent to Kong Admin
* What endpoint did you call in Kong gateway.
* What happened when you called it.

**Comment by harsh4870** [comment]
@ropi95  any solution or update please you can share

**Comment by EliuX** [comment]
I got this problem and I realized that keycloak, in your localhost, always creates tokens where the `iss` claim is something like

> `http://127.0.0.1:8080/auth/realms/<realm>`

So, when setting up this plugin in kong, if you specify your param `config.allowed_iss` with this format, instead of using `localhost`, you may solve your problem.
IMHO, it would help a ticket for changing references in the README.md from `localhost` to `127.0.0.1`.

**Comment by sujitrs** [comment]
check the URL used in request to issue a token. It should match with ```congif.allowed_iss```
