### ISSUE TITLE
error:{"timestamp":1569220402982,"status":401,"error":"Unauthorized","message":"Unable to authenticate using the Authorization header","path":"/api/"}

### ISSUE THREAD

**Issue by shanleyHe** [gbbirkisson/kong-plugin-jwt-keycloak#15]
curl -X POST http://ip:port/services -d "name=test" -d "url=http://ip:port/api/" |python -m json.tool

**Comment by gbbirkisson** [comment]
I am closing this issue because I have no idea what it is about or what you are trying to do.
