### ISSUE TITLE
How to enable basic auth and jwt-keycloak plugin for a single service

### ISSUE THREAD

**Issue by vaishnoavi** [gbbirkisson/kong-plugin-jwt-keycloak#16]
Hello @gbbirkisson ,

I am using your plugin and now I have a requirement to enable both basic-auth and jwt-keycloak plugin for a single service. From the documentation https://docs.konghq.com/1.4.x/auth/#multiple-authentication, I created an anonymous user and mapped them in the configs for basic-auth and jwt-keycloak plugin. 
I also added request termination as suggested, but now the requests made via basic auth only work whereas the one with jwt-keycloak doesn't.

Can you provide me some information to fix the issue?

Steps : 
1. enable both plugins for a service
2. created an anonymous user
3. enable anonymous user for both the plugins 
4. add request termination for the service (tried with exit code 401)
5. requests via basic auth works but the ones made with jwt-keycloak doesn't

**Comment by gbbirkisson** [comment]
I do not have much experience with this. Do you get a 401 when trying calling the service with a token?

The Basic Auth plugin priority is 1001 but the default priority for this plugin is 1005, meaning that the this plugin is run first. You can flip it by setting the env variable JWT_KEYCLOAK_PRIORITY to 1000 or something lower. Do your tests again post the result.

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
