### ISSUE TITLE
Keycloak authorization server

### ISSUE THREAD

**Issue by canattofilipe** [gbbirkisson/kong-plugin-jwt-keycloak#19]
Hi all,

The Keycloak documentation describes an [authorization services guide](https://www.keycloak.org/docs/latest/authorization_services/index.html), abou it the documentation says:

_"Keycloak is based on a set of administrative UIs and a RESTful API, and provides the necessary means to create permissions for your protected resources and scopes, associate those permissions with authorization policies, and enforce authorization decisions in your applications and services."_

If I use kong-plugin-jwt-keycloak to make authorization decisions I stop using keycloak authorization services, right ?. What are pros and cons abou this approach.

**Comment by gbbirkisson** [comment]
This plugin validates tokens without calling Keycloak (except calls to update public keys from time to time). It validates authorization with the token claims, not by calling Keycloak to check permissions. In reality, this plugin has little to do with Keycloak and is more just a OIDC plugin that can verify Keycloak claims.

I have not used Keycloak authorization services, just this plugin. So I would argue you are in a better position to weigh the pros and cons.

**Comment by canattofilipe** [comment]
@gbbirkisson Thanks for replying, I have never used Keycloak authorization services too.
