### ISSUE TITLE
Failure on first token validation

### ISSUE THREAD

**Issue by jschirrmacher** [gbbirkisson/kong-plugin-jwt-keycloak#21]
I use Kong 2.0.2 with the most current version of jwt-keycloak plugin. I start the gateway and a keycloak instance in the test environment every morning. When I obtain a JWT from keycloak and access the API gateway the first time with this token, I get an error "Unable to get public key for issuer". When I try again, all works correctly.

I've set the log level to 'debug' and see a warning
```
2020/06/09 06:20:43 [debug] 25#0: *141217 [lua] base_plugin.lua:26: access(): executing plugin "jwt-keycloak": access
  | 2020/06/09 06:20:43 [warn] 25#0: *141217 [lua] _G write guard:12: __newindex(): writing a global lua variable ('well_known_endpoint') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
  | stack traceback:
  | ...ocal/share/lua/5.1/kong/plugins/jwt-keycloak/handler.lua:182: in function 'validate_signature'
  | ...ocal/share/lua/5.1/kong/plugins/jwt-keycloak/handler.lua:288: in function 'do_authentication'
  | ...ocal/share/lua/5.1/kong/plugins/jwt-keycloak/handler.lua:339: in function <...ocal/share/lua/5.1/kong/plugins/jwt-keycloak/handler.lua:325>, client: 10.0.0.123, server: kong, request: "GET /mds/policies HTTP/1.1", host: "example.com", referrer: "https://example.com/ "
```

Could it have something to do with that and could it be solved by making the variable `well_known_endpoint` in https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/blob/master/src/handler.lua#L182 local?

**Comment by gbbirkisson** [comment]
Sounds like Keycloak fails to server the first request.

**Comment by harsh4870** [comment]
@jschirrmacher  any update on this solution ?

**Comment by jschirrmacher** [comment]
My "first validation" problem seems to be solved, though I don't know how. At least, it seems not to have anything to do with the jwt-keycloak plugin, because I still use the same version as before. I will close this issue therefore now.

The warning in debug mode, however, will most likely still exist, because the code line is unchanged.

**Comment by harsh4870** [comment]
everything working for me. Thanks a lot for update.
