### ISSUE TITLE
Guidance on implementing Authorization Scope

### ISSUE THREAD

**Issue by harsh4870** [gbbirkisson/kong-plugin-jwt-keycloak#22]
hi @gbbirkisson great work, thanks for plugin.

i am looking for help on how to setup authentication like **Github** using Keycloak & Kong.

i am using Kong API gateway with Keycloak along with **OIDC** plugin and **kong-plugin-jwt-keycloak**.

as in **GitHub** we have **organization** repo and each user has different access in an organization repo (read/write) or i can add a specific user to the organization with only one repository access.

i think Github manage this by forming URL 

https://github.com/org-name/username/reponame and restricting user at API gateway level if no access there. 

can you please help me how to achieve it using same with **kong-plugin-jwt-keycloak** ? 

i think for that same i might have to use **authorization scope** but how to filter using plugin ? 

![Selection_079](https://user-images.githubusercontent.com/15871000/86211476-1760df80-bb94-11ea-81cc-50aa2da6586d.png)

**Comment by gbbirkisson** [comment]
This plugin has a very clear README: use scope or roles claims to control access to endpoints. How you set that up is up to you. This case seems a little complicated but it might be achievable.

You can use https://jwt.io/ to see the claims that are in your issued tokens. You can also easily see in the source code how the claims are validated. I hope you are able to work this out but I am not going to try to design this for you.

Best of luck, hope it works out.

**Comment by canattofilipe** [comment]
@harsh4870 I created a solution using kong-plugin-jwt-keycloak and another one called [pep-kong](https://github.com/dojot/kong/tree/feature/keycloak-10.0.1/plugins/pepkong) to do authorization using Keycloak authorizarion services, take a look at the [project](https://github.com/dojot/kong/tree/feature/keycloak-10.0.1) maybe it can help you.

**Comment by harsh4870** [comment]
@canattofilipe  Sure, i will try it. Thanks a lot for the heads up.
