### ISSUE TITLE
Getting response:  Access token does not have the required scope/role: Missing required scope

### ISSUE THREAD

**Issue by shashankjain43** [gbbirkisson/kong-plugin-jwt-keycloak#23]
1. Created and containerize,  kong image as below:
FROM kong:2.0.5
USER root
RUN  luarocks install kong-oidc
RUN  luarocks install kong-plugin-jwt-keycloak
ENV KONG_PLUGINS=bundled,oidc,jwt-keycloak

2. containerized keycloak with version 11.0.0

3. Added plugin to my route as below:
curl --location --request POST 'localhost:9001/routes/87a1667b-4013-4607-bddb-6f35f9b92fb5/plugins' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'name=jwt-keycloak' \
--data-urlencode 'config.allowed_iss=http://host.docker.internal:8080/auth/realms/myrealm' \
--data-urlencode 'config.scope=ihd-scope'

4. Getting token through kong from keycloak:
curl --location --request POST 'http://localhost:8000/getToken' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=myclient-ihd' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_secret=<SECRET>' \
--data-urlencode 'scope=ihd-scope'

{
    "access_token": "<ACCESS_TOKEN>",
    "expires_in": 36000,
    "refresh_expires_in": 1800,
    "refresh_token": "<REFRESH_TOKEN>",
    "token_type": "bearer",
    "not-before-policy": 0,
    "session_state": "e06d665e-6834-49a4-b8ff-e09a7f484e38",
    "scope": "ihd-scope"
}

4. Accessing my app PAI through kong as below:

curl --location --request POST 'http://localhost:8000/ihds/accountId/isInHome' \
--header 'Authorization: Bearer <ACCESS_TOKEN>'

5. getting a response: 
{
    "message": "Access token does not have the required scope/role: Missing required scope"
}

My issue is that although client_id=myclient-ihd contains the scope= ihd-scope as represented by point.5 above, Then why I am getting the message "Missing required scope".

Please help me if I am missing any config while adding plugin to my route.

**Comment by gbbirkisson** [comment]
Well, I'm guessing that scope is not in the token claims. Go to https://jwt.io/, paste your token in there, and look at the decoded payload. How does it look like? Does it contain the `ihd-scope`?

**Comment by thiagodiogo** [comment]
I had the same issue here.
It appears to be a bug when using a scope with "-" in the name.
I changed mine to use "_" and it worked.

It appears to be a problem here:
https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/blob/5f4b6cb2b067da3a473b7377abd7057ad06172e8/src/validators/scope.lua#L11

But I am not sure how to fix in lua :)
