### ISSUE TITLE
[FEATURE/QUESTION] Forward value from jwt token to service in header

### ISSUE THREAD

**Issue by 4n70w4** [gbbirkisson/kong-plugin-jwt-keycloak#26]
Hi! Thanks for plugin!

I have a need to pass a value from the jwt-token, for example, `sub` and forward it to the target service, for example, as a header.

![image](https://user-images.githubusercontent.com/38257723/94747003-a691b500-0386-11eb-92a0-8896728b3b28.png)

I didn't understand if there was such a possibility and how to implement it.

**Comment by 4n70w4** [comment]
For example: set rate limit by value from jwt-token.

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
