### ISSUE TITLE
[FEATURE/QUESTION] Is this plugin supported in DBless mode and can it be configured using KongPlugin resource?

### ISSUE THREAD

**Issue by zachjsh** [gbbirkisson/kong-plugin-jwt-keycloak#27]
Thanks for developing this plugin! We are planning to use Kong deployed in Kubernetes in DBless mode. I see all of the examples use the admin API, from what I understand is only available in Kong normal mode (with DB). We'd like to be able to configure this with the KongPlugin resource, https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/getting-started.md#using-plugins-in-kong, and attach it an ingress / service as needed. Is this possible? If so are there any examples for this use case?

**Comment by phainamikaze** [comment]
I'm planning to use Kong deployed in Kubernetes in **DBless** mode to.
need to support with dbless

**Comment by gbbirkisson** [comment]
Hi. It is great that you find this plugin useful. I am not maintaining it any longer. Like the README states at the top:

> **Attention**: I will no longer be maintaining this plugin. Thanks for all the positive feedback and interest in this project. Feel free to fork and keep it alive. Cheers!

I have no plans to support dbless. You are welcome to fork and implement it yourself. If you do, I would love a PR.

Good luck

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
