### ISSUE TITLE
Caching customers by custom cache key may lead to erroneous behavior

### ISSUE THREAD

**Issue by burdikov** [gbbirkisson/kong-plugin-jwt-keycloak#28]
Hi,

Caching using custom cache key ([link](https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/blob/5f4b6cb2b067da3a473b7377abd7057ad06172e8/src/handler.lua#L217))
```lua
consumer_cache_key = "custom_id_key_" .. consumer_id
consumer, err = kong.cache:get(consumer_cache_key, nil, load_consumer_by_custom_id, consumer_id, true)
```
prevents Kong from proper automatic invalidation of corresponding cache record. This leads to different errors when
a consumer is updated, deleted or recreated (we are stuck at constant 401 from acl plugin). Since usage of custom cache key is justified, handler should create it's own listener for kong events to handle invalidation (as described [here](https://docs.konghq.com/2.2.x/plugin-development/entities-cache/#manual-cache-invalidation)).

**Comment by burdikov** [comment]
I have prepared a needed change and will open a PR

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
