### ISSUE TITLE
Support rotating public keys

### ISSUE THREAD

**Issue by laurentverbruggen** [gbbirkisson/kong-plugin-jwt-keycloak#3]
Currently the plugin only supports 1 public key per issuer. However, certificates expire and when that happens you'll need to update the public key with a new certificate making all access tokens issued with the previous (possibly still valid) public key invalid. 

Of course consumer can just collect a new access token and retry, but it causes unexpected errors.
Is it an option to add this feature?

**Comment by gbbirkisson** [comment]
Fixed
