### ISSUE TITLE
how to force kong-plugin-jwt-keycloak to check list of scopes

### ISSUE THREAD

**Issue by alihossein** [gbbirkisson/kong-plugin-jwt-keycloak#32]
Hi. thank you for a great plugin.
I want the service to be available when both scopes are in the token (for example opened view_profile) but I read the Readme : 

`A list of scopes the token must have to access the api, i.e. ["email"]. The token only has to have one of the listed scopes to be authorized.`

 How can I do this?

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
