### ISSUE TITLE
Does the plugin support Keycloak's Authorization Services / resource & scope permission based authorization?

### ISSUE THREAD

**Issue by kassemdarwish** [gbbirkisson/kong-plugin-jwt-keycloak#33]
Hello,

I'm wondering if the plugin currently supports Keycloak's [authorization services](https://www.keycloak.org/docs/latest/authorization_services/index.html) and if not, are there any plans to do so in the near future? 

Thanks.

**Comment by gruummy** [comment]
@kassemdarwish  I do not fully understand the point ?
What functionality in detail you would want the have added in addition to this plugin ?

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
