### ISSUE TITLE
Readme update proposal: additional configuration to enable the plugin

### ISSUE THREAD

**Issue by jp-chl** [gbbirkisson/kong-plugin-jwt-keycloak#35]
> _At least in Kong version 2.4.0, you may also need to add the line "```plugins = bundled,jwt-keycloak```" in Kong configuration (e.g. ```kong.conf``` file), and restart Kong (```kong restart``` command). [More info at Kong documentation](https://docs.konghq.com/gateway-oss/1.1.x/plugin-development/distribution/#load-the-plugin)._

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
