### ISSUE TITLE
Consumer match

### ISSUE THREAD

**Issue by vic-pic** [gbbirkisson/kong-plugin-jwt-keycloak#36]
Hi, first thanks for this plugin.
One feature I love is the ability to match the consumer in kong, but I cannot make it working: I set the "consumer_match" and the "consumer_match_claim_custom_id" config, but I always receive the "Unable to find consumer for token" error message. What am I doing wrong?

Thanks ENx

**Comment by GeeinHub** [comment]
Hi,
I also met this problem, could anyone give some tips?

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
