### ISSUE TITLE
Assign different roles in plugin jwt-keycloak Kong

### ISSUE THREAD

**Issue by magatoDev** [gbbirkisson/kong-plugin-jwt-keycloak#37]
Hi friends!,

I've implement this plugin and I wish to know how can I apply differents roles in function of its method’s names or service's name. 
I mean. I've two services in the server that are exposed by Kong, these services have different names methods and different names service, but have the same path, both are called with GET.

I don't know if you can understood me. But, if I could to do an abstract about this trouble, I could to say that just I need to assign different roles through “jwt-keycloack” in function of the methods names or name service.

I've attached a PDF with information -> [Services.pdf](https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/files/7144653/Services.pdf)

Thank you very much in advance.

Best regards!

**Comment by gruummy** [comment]
@magatoDev Is your question still a valid one ?
... or have you already recognozed that the "route" in kong in first line is the problem ?

A "service" is only involved by kong when the "route" was choosen and then the processing of the request is forwarded to the "service"

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
