### ISSUE TITLE
Use Keycloak Endpoint Configuration

### ISSUE THREAD

**Issue by laurentverbruggen** [gbbirkisson/kong-plugin-jwt-keycloak#4]
Keycloak provides OpenID Connect endpoint configuration for its realms with the following url: https://<host>/auth/realms/<realm>/.well-known/openid-configuration

This URL contains a `jwks_uri` field that will return you the public keys to validate the access tokens.
JSON Web Key Set (https://tools.ietf.org/html/rfc7517) is standardized and will return potentially several public keys, which also solves #3 .

Another field in the configuration is the `issuer`. This will allow you to avoid configuring issuers on the plugin itself by simply configuring the configuration url on the route/service.

This feature will greatly benefit this plugin imo.

**Comment by gbbirkisson** [comment]
This is a a very nice idea. Thank you for the suggestion. I will look into this when I have some spare time.

**Comment by gbbirkisson** [comment]
I have implemented this logic and updated the documentation
