### ISSUE TITLE
{"message":"Unable to get public key for issuer"}

### ISSUE THREAD

**Issue by Chitraaansh** [gbbirkisson/kong-plugin-jwt-keycloak#45]
Hi,
How can I make sure that Kong has access to the well known endpoint http:///auth/realms/master/.well-known/openid-configuration and the jwks_uri http:///auth/realms/master/protocol/openid-connect/certs. Do I need to configure these URLs anywhere in Kong? I am facing this issue as well, {"message":"Unable to get public key for issuer"}. Your help with the steps would be grateful.

**Comment by gbbirkisson** [comment]
I am about to archive this repository. Please move your issues/PRs the successor of this repo: https://github.com/telekom-digioss/kong-plugin-jwt-keycloak
