### ISSUE TITLE
Unable to get public key for issuer

### ISSUE THREAD

**Issue by jerryhan77** [gbbirkisson/kong-plugin-jwt-keycloak#8]
Hi,

After setup everything, when access the kong, I got error: 
`{"message":"Unable to get public key for issuer"}`

The keycloak server is 3.4.3.Final.

The jwt token was sigined by realm rsa key. Which is different from the public key get from 'jwks_uri'。

Don't know where were wrong.

How can I just specify the keycloak public key?

Thanks

**Comment by jerryhan77** [comment]
Update:

All component are running in openshift 3.11.

kong error log:
```
2019/05/23 07:40:35 [error] 37#0: *160648 [kong] handler.lua:179 [jwt-keycloak] failed to get from node cache: Failed calling url https://keycloak.paas.com/auth/realms/npmis/.well-known/openid-configuration, client: 10.129.2.1, server: kong, request: "GET /echo HTTP/1.1", host: "api.paas.com"
```

Look like cannot fetch keycloak configuration.

But I can confirm the openid-configuration url can be fetched correctly by curl in kong container.

I'm stuck in here.

Any suggestion?

**Comment by gbbirkisson** [comment]
Hi,
I found a problem when running Keycloak 3.4.3 an I fixed it in the [latest release](https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/releases/tag/v1.0.2). Please update your plugin.

So when you apply the plugin to an endpoint, be sure to set the `allowed_iss` to your keycloak instance i.e.  `http://<HOST>/auth/realms/master`.

Also make sure that Kong has access to the well known endpoint `http://<HOST>/auth/realms/master/.well-known/openid-configuration` and the jwks_uri `http://<HOST>/auth/realms/master/protocol/openid-connect/certs`.

That should do the trick.

**Comment by jerryhan77** [comment]
Thanks for your quick fix.

I have tested new version. But still got same error on Keycloak 3.4.3.

Keycloak 6.0.1 test passed.

Compare the `http://<HOST>/auth/realms/master/protocol/openid-connect/certs` result from two keycloak:
```
Keycloak 3.4.3
$ curl -s https://keycloak3/auth/realms/npmis/protocol/openid-connect/certs | python -mjson.tool
{
    "keys": [
        {
            "alg": "RS256",
            "e": "AQAB",
            "kid": "jlNtYV5gJOoJoF525j0J-arPmTdIw77j7QJHFqXOFV0",
            "kty": "RSA",
            "n": "mwxlcXeP0nOl5st__2rVb0PLOgGogSqYI2HKs1AaBj6yYloKLbt_RrkwTpAWXptIYdYPV8Zgymnf79sYurEGDB1eJNZUALGRy8I1wAozOTERZONhkEwrmciVCIWnXbkEx1UqjDOl39VVp1ViV9QWJIJ69x6vusoMzG24qjr4WljOqigTAAsw8Tej8p1PqCWp9k6jgOmu_BwR2d-ETOSlBzapo6ppTrliiRxHZp1uaQE5yGTS9E3_pKL1iHqsWREtTgSMeDcAFZlH-WDQtnmrRC_KX6d7kb-Fdp3O9NtR0n4wsrb-7KipjkaJr5XaDJj1N6i51dY3I9cDWWyIg8qUjQ",
            "use": "sig"
        }
    ]
}

Keycloak 6.0.1
$ curl -s http://keycloak6/auth/realms/master/protocol/openid-connect/certs | python -mjson.tool
{
    "keys": [
        {
            "alg": "RS256",
            "e": "AQAB",
            "kid": "c1LlkJYfnJWC3Quu9vq-ZFVpbCT3NkYuLFf2ShSBU7k",
            "kty": "RSA",
            "n": "jhZLidzM0HzZf2qAXl7Yeio0M467aCaYq-mRzXo04eq4BnT5xHe84t7F6sF_u0R8zhICwCCofgV_xZRij2BwuMILuaVYpwZ_Wxt7_qQbeMafm_kx9FkEMTqaR4K0oflnR6BAByCN46Og4wWPXW4FULprua9J8rUkOKJSD9dxfQkYrdS-2mBn66W05vCTRemCV-Hn03mxVYBmsvuJ19A3xVQQ0VjKDJkPqR58RlUPE0T-CvgNwsXx-gzgFE3_9NEGrK0bJUYUlIewhr1g6kbPj-lIVS9odaj8u6KvjmNg8MSr5NAXU7gbnTbe4gj1FsAVHXZC8aUgkG6npQYqfb6gKQ",
            "use": "sig",
            "x5c": [
                "MIICmzCCAYMCBgFq566AUTANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMTkwNTI0MDIzMDM0WhcNMjkwNTI0MDIzMjE0WjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCOFkuJ3MzQfNl/aoBeXth6KjQzjrtoJpir6ZHNejTh6rgGdPnEd7zi3sXqwX+7RHzOEgLAIKh+BX/FlGKPYHC4wgu5pVinBn9bG3v+pBt4xp+b+TH0WQQxOppHgrSh+WdHoEAHII3jo6DjBY9dbgVQumu5r0nytSQ4olIP13F9CRit1L7aYGfrpbTm8JNF6YJX4efTebFVgGay+4nX0DfFVBDRWMoMmQ+pHnxGVQ8TRP4K+A3CxfH6DOAUTf/00QasrRslRhSUh7CGvWDqRs+P6UhVL2h1qPy7oq+OY2DwxKvk0BdTuBudNt7iCPUWwBUddkLxpSCQbqelBip9vqApAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAACC8NXQe8p27PjiyymXjBdWsyJI11bnm8SNSKgISgtWlv2w00A6OyhJROTOFdXKq0SE35uBryBeVpfmUGbuXiX3ttVnXsIFfKgoMagLP3PsE6dRu0+q+Ig6zM7iC20HOrC8at1J/efragL6EQoAK/5SIh+8RugLUypzQw9uTRqJ7L3lO+iaGuKLv9o547jOSbKqieSmTQQhinm2CKkme1LItmVZT1DNA27vN9NM17Xw7C9Oq35OTyDAAO8OnxdG6CKj8CCXpdY/vA/aGr9qxGJLCvJPAXLPIWIiVAktquZznz31BkOdkTNtXeUgQnvKyJmIOe9ufkfupnyTDlGY+NI="
            ],
            "x5t": "ARAhpDZ88sPpBmT9jWY8cby9PUI",
            "x5t#S256": "-RDwGW8IcalGHmfX_TmN5ccq380obXGiLNug0y79pWA"
        }
    ]
}
```

It seem's keycloak 3.4.3 provide less pub key info than 6.0.1.

I think this cause this plugin not work on keycloak 3.4.3.

Wish you can fix this.

Thanks

**Comment by jerryhan77** [comment]
Hi,

Thanks for the quick fix.

I try the new version, still got same error.

But after I change the keycloak url from https to http, your plugin work fine.

The keycloak's https service use an valid Let’s Encrypt Certificates.  Use `curl` command in kong container can fetch keycloak without any issue.

I also tested kong-oidc plugin in same kong service, which use same keycloak https service without any issue.

So, I'm confused, how to fix this.

Thanks

**Comment by gbbirkisson** [comment]
I have tested this plugin with https and it should work fine. This is probably some misconfiguration:

Lets start by taking a look at the access token issued by keycloak that you are using. Get a new access token from keycloak and run in a terminal:

```bash
echo "YOURTOKEN" | tr '.' '\t' | awk '{print $2}' | base64 -d 2>/dev/null | jq
```

It should output something like:

```json
{
  "jti": "20732536-e59a-43bd-91ed-745dfc611306",
  "exp": 1558696532,
  "nbf": 0,
  "iat": 1558696472,
  "iss": "http://localhost:8080/auth/realms/master", <- ISS_CLAIM
  "aud": "4697e40d-0e94-4c08-8afe-ada1cb44a288",
  "sub": "16e967c1-7d99-448a-831d-33c99051d54b",
  "typ": "Bearer",
  "azp": "4697e40d-0e94-4c08-8afe-ada1cb44a288",
  "auth_time": 0,
  "session_state": "ac698fe8-061b-46b3-960b-90e73f705882",
  "acr": "1",
  "allowed-origins": [],
  "realm_access": {
    "roles": [
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "clientId": "4697e40d-0e94-4c08-8afe-ada1cb44a288",
  "clientHost": "172.17.0.1",
  "preferred_username": "service-account-4697e40d-0e94-4c08-8afe-ada1cb44a288",
  "clientAddress": "172.17.0.1",
  "email": "service-account-4697e40d-0e94-4c08-8afe-ada1cb44a288@placeholder.org"
}
```

The iss field in the token is what the plugin will look at to retrieve public keys. So in the Kong container you should be able to run `curl ISS_CLAIM_IN_TOKEN/.well-known/openid-configuration` and get a valid response. So in this case it would be `curl http://localhost:8080/auth/realms/master/.well-known/openid-configuration`. Does that work?

If that does work and you still have the same issue. I need a way to replicate this locally or I need more concrete information, such as the iss claim in token and the url to the keycloack server.

**Comment by unusual-thoughts** [comment]
Are you sure you tested with https in the discovery endpoint (and public key endpoint) ?
(which is required by the standard BTW https://openid.net/specs/openid-connect-discovery-1_0.html#TLSRequirements)

**Comment by gbbirkisson** [comment]
Hey @jerryhan77. With some help from @unusual-thoughts I think we might have a fixed this issue. Can you verify version 1.0.3 works for you?

**Comment by jerryhan77** [comment]
Yes, I can confirm version 1.0.3 works for me.

Thanks guys! @gbbirkisson  @unusual-thoughts

**Comment by pbajoit** [comment]
I have the same error message "Unable to get public key from issuer" with kong-plugin-jwt-keycloak:latest on kong 1.2.1

I observed that the issuer of my certificate (TERENA) was not in the built-in certificates of alpine so a curl command showed very well the problem with a similar message
`docker exec dc-kong_kong_1 sh -c "curl https://MY-HOST:8443/auth/realms/develop/.well-known/openid-configuration"`

After adding the TERENA certificate I get curl to work properly and access the JSON as expected, however the lookup of the URL by the plugin still fails with the same message
Is Lua working with its own list of CA's ?

The CA certificate was added as described in the how-to of alpine :
```
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY ./TERENASSLCA3.crt /usr/local/share/ca-certificates/TERENASSLCA3.crt
RUN update-ca-certificates
```

**Comment by Chitraaansh** [comment]
Hi @gbbirkisson,
How can I make sure that Kong has access to the well known endpoint http://<HOST>/auth/realms/master/.well-known/openid-configuration and the jwks_uri http://<HOST>/auth/realms/master/protocol/openid-connect/certs. Do I need to configure these URLs anywhere in Kong? I am facing this issue as well, {"message":"Unable to get public key for issuer"}.
