### ISSUE TITLE
support https for issuer/public key discovery

### ISSUE THREAD

**Issue by unusual-thoughts** [gbbirkisson/kong-plugin-jwt-keycloak#9]
currently `socket.http` is used which doesn't support TLS

**Comment by unusual-thoughts** [comment]
see https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/pull/10

**Comment by unusual-thoughts** [comment]
Just a suggestion: maybe use `socket.url.parse` to parse url instead of a custom regex ?

**Comment by gbbirkisson** [comment]
Awesome suggestions. I merged your pull request and made some modifications to make the tests pass. Also used `socket.url.parse`. Thanks for you help. Can you verify version 1.0.3 works for you?

**Comment by unusual-thoughts** [comment]
Thanks! In theory `ssl.https` should also work with plain http connections though.
On another note, is there anything really specific to Keycloak in this plugin? Looks like this is all standard oidc. I'm not actually using keycloak BTW.

**Comment by gbbirkisson** [comment]
When running tests on your pull request `ssl.https` did not seem to work with `http`, that is why I added some more changes. If you have a more elegant solution than me and running `make test` passes, another pull request is always appreciated.

As for the `keycloak` part in the plugins name, I guess it is not really Keycloak specific. I wonder if the `roles`, `realm_roles` and `client_roles` part of the configuration would work with something other than Keycloak. What server are you using?

**Comment by gbbirkisson** [comment]
Seems this issue is resolved. I am closing it.
